version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - backend
  
  firebase:
      build:
          context: .
          dockerfile: firebase.dockerfile
      ports:
      - 8806:8806
      command: gcloud beta emulators firestore start --host-port=0.0.0.0:8806
      volumes:
          - firebase_data:/opt/data
      networks:
          - backend

  cloud-storage:
    container_name: cloud-storage
    build:
        context: .
        dockerfile: cloud_storage.dockerfile
    restart: always
    ports:
    - 8888:8888
    networks:
      - backend
volumes:
  firebase_data:
    name: firebase_data
  postgres_data:
    name: postgres_data

networks:
  backend: