version: '3.7'
services:
  test:
    build:
      context: .
      target: test
      cache_from: 
      - $CACHE_FROM
    command: 
    - poetry
    - run
    - invoke
    - compose:warmup
    depends_on:
      - mongo
    links:
      - mongo
    restart: always
