version: '3.7'
services:
  mongo:
    image: mongo:4.4 
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
    - mongodb_data:/data/db
    networks:
      - mongodb_backend
volumes:
  mongodb_data:
    name: mongodb_data

networks:
  mongodb_backend: